rm -f ../Application/app_hooks.c~
rm -f ../Application/app_main.c~
rm -f ../Application/bsp.c~
rm -f ../Application/debug.c~
rm -f ../Application/inc/app_cfg.h~
rm -f ../Application/inc/bsp.h~
rm -f ../Application/inc/cpu_cfg.h~
rm -f ../Application/inc/debug.h~
rm -f ../Application/inc/includes.h~
rm -f ../Application/inc/key.h~
rm -f ../Application/inc/light_ctrl.h~
rm -f ../Application/inc/misc_lib.h~
rm -f ../Application/inc/nor_flash.h~
rm -f ../Application/inc/os_cfg.h~
rm -f ../Application/key.c~
rm -f ../Application/light_ctrl.c~
rm -f ../Application/misc_lib.c~
rm -f ../Application/nor_flash.c~
rm -f ../RTE/CMSIS/RTX_Conf_CM.c~
rm -f ../RTE/Device/STM32F103C8/RTE_Device.h~
rm -f ../RTE/Device/STM32F103C8/stm32f10x_conf.h~
rm -f ../RTE/Device/STM32F103C8/system_stm32f10x.c~
rm -f ../RTE/RTE_Components.h~
rm -f ../uCOS-II/Ports/os_cpu.h~
rm -f ../uCOS-II/Ports/os_cpu_c.c~
rm -f ../uCOS-II/Ports/os_dbg.c~
rm -f ../uCOS-II/Source/os_cfg_r.h~
rm -f ../uCOS-II/Source/os_core.c~
rm -f ../uCOS-II/Source/os_dbg_r.c~
rm -f ../uCOS-II/Source/os_flag.c~
rm -f ../uCOS-II/Source/os_mbox.c~
rm -f ../uCOS-II/Source/os_mem.c~
rm -f ../uCOS-II/Source/os_mutex.c~
rm -f ../uCOS-II/Source/os_q.c~
rm -f ../uCOS-II/Source/os_sem.c~
rm -f ../uCOS-II/Source/os_task.c~
rm -f ../uCOS-II/Source/os_time.c~
rm -f ../uCOS-II/Source/os_tmr.c~
rm -f ../uCOS-II/Source/ucos_ii.c~
rm -f ../uCOS-II/Source/ucos_ii.h~
