indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/app_cfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/bsp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/cpu_cfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/debug.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/includes.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/key.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/light_ctrl.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/misc_lib.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/nor_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/inc/os_cfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../config/filelist.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../RTE/Device/STM32F103C8/RTE_Device.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../RTE/Device/STM32F103C8/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../RTE/RTE_Components.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Ports/os_cpu.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_cfg_r.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/ucos_ii.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/app_hooks.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/app_main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/bsp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/debug.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/key.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/light_ctrl.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/misc_lib.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../Application/nor_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../RTE/CMSIS/RTX_Conf_CM.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../RTE/Device/STM32F103C8/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Ports/os_cpu_c.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Ports/os_dbg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_core.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_dbg_r.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_flag.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_mbox.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_mem.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_mutex.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_q.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_sem.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_task.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_time.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/os_tmr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ../uCOS-II/Source/ucos_ii.c
